[package]
name = "numeri_causali"
version = "0.1.0"
authors = ["robertomartina <roberto.martina@tecnodiario.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
